apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controller
  namespace: data-platform
  labels:
    strimzi.io/cluster: meridian 
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: persistent-claim
    size: 10Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi

---

apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker
  namespace: data-platform
  labels:
    strimzi.io/cluster: meridian 
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: persistent-claim
    size: 20Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 2Gi

---

apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: meridian
  namespace: data-platform
spec:
  kafka:
    version: 4.3.1
    metadataVersion: 4.3-IVO
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}
