apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: meridian-postgres
  namespace: data-platform

spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-system-trixie

  storage:
    size: 5Gi
    storageClass: csi-hostpath-sc

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
